### ISSUE TITLE
Is Google identify the page is an AMP page

### ISSUE THREAD

**Issue by 199911** [choumx/amp-pwa#7]
From the documentation, seems Google identify the pages by the `<html amp>`
Can the google search engine identify that PWA page is AMP and showing the "AMP" tag next to serach result like this?
![](https://www.ampproject.org/static/img/case-studies/terra_framed1.png)

**Comment by choumx** [comment]
This will automatically happen if your PWA itself is [valid AMP](https://www.ampproject.org/docs/guides/debug/validate) -- we call this pattern "AMP as canonical". For instance, [AMPByExample.com](https://ampbyexample.com) is a PWA that is valid AMP (e.g. it uses the `<amp-install-serviceworker>` AMP extension to install the service worker rather than via custom JS).

"AMP-PWA", as exhibited by this repository, is a slightly different pattern that embeds AMP content into a non-AMP shell. In this case, only the AMP content pages will show up in Google Search with the AMP logo.
